//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 12:56:44 PM EDT 
//


package org.alfresco.museum.ucm.config.autogen;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.alfresco.museum.ucm.config.autogen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.alfresco.museum.ucm.config.autogen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UCMConfig }
     * 
     */
    public UCMConfig createUCMConfig() {
        return new UCMConfig();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel }
     * 
     */
    public UCMConfig.DataModel createUCMConfigDataModel() {
        return new UCMConfig.DataModel();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Types }
     * 
     */
    public UCMConfig.DataModel.Types createUCMConfigDataModelTypes() {
        return new UCMConfig.DataModel.Types();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Types.Type }
     * 
     */
    public UCMConfig.DataModel.Types.Type createUCMConfigDataModelTypesType() {
        return new UCMConfig.DataModel.Types.Type();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Aspects }
     * 
     */
    public UCMConfig.DataModel.Aspects createUCMConfigDataModelAspects() {
        return new UCMConfig.DataModel.Aspects();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Aspects.Aspect }
     * 
     */
    public UCMConfig.DataModel.Aspects.Aspect createUCMConfigDataModelAspectsAspect() {
        return new UCMConfig.DataModel.Aspects.Aspect();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Types.Type.Property }
     * 
     */
    public UCMConfig.DataModel.Types.Type.Property createUCMConfigDataModelTypesTypeProperty() {
        return new UCMConfig.DataModel.Types.Type.Property();
    }

    /**
     * Create an instance of {@link UCMConfig.DataModel.Aspects.Aspect.Property }
     * 
     */
    public UCMConfig.DataModel.Aspects.Aspect.Property createUCMConfigDataModelAspectsAspectProperty() {
        return new UCMConfig.DataModel.Aspects.Aspect.Property();
    }

}
